# Generated by Django 3.2.8 on 2021-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_map_api', '0002_auto_20210915_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buy_price', models.DecimalField(decimal_places=14, max_digits=1000)),
                ('sell_price', models.DecimalField(decimal_places=14, max_digits=1000)),
            ],
        ),
    ]
