# Generated by Django 3.2.8 on 2021-11-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_map_api', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=14, max_digits=1000)),
                ('received_date', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='warehouse_map_api.position'),
        ),
    ]
