# Generated by Django 3.2.8 on 2021-11-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_map_api', '0004_auto_20211031_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='warehouse_map_api.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='warehouse_map_api.product')),
            ],
        ),
    ]
